# Generated by Django 5.1 on 2024-08-23 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMentor',
            fields=[
                ('studentmentorid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('mentorcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.mentor')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student')),
            ],
        ),
    ]
